name: Android CI

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      [ "master" ]
  pull_request:
    branches:
      [ "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: pwd;chmod +x /home/runner/work/easycontrol-watch/easycontrol-watch/gradlew
    - name: Build with Gradle
      working-directory: easycontrol
      run: /home/runner/work/easycontrol-watch/easycontrol-watch build
    - name: Package Files
      run: pwd

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-package
        path: /home/runner/work/easycontrol-watch/easycontrol-watch/app/src/main/res/raw/
